#!/usr/bin/perl
#
# Copyright 2000 Daniel Klein, dvk@lonewolf.com - Unlimited distribution and
# use permitted as long as this copyright notice is included in all copies.
#
# Check /var/log/messages for failed SU attempts - keep track of how many, by
# whom, and to whom.  Start by opening the file and complaining if we can't.
#
die "Can't open /var/log/messages\n" unless open(LOG, "/var/log/messages");

#
# Here's the main work loop - just read in a line, and if it looks like this:
#	Feb 14 18:04:53 calf su: BAD SU dvk to root on /dev/ttyp0
# then extract the "from" (dvk) and the "to" (root).
#
while (<LOG>) {
	next unless /su\(.*authentication failure/;

	$total++;
	/su\(.*logname=(\w+) .* user=(\w+)/;	# Simple pattern match
	$from{$1}++;
	$to{$2}++;
	}

exit if $total < 1;			# Arbitrary threshhold

print "\n$total BAD SU attempts\n\n";

for $name (keys %from) {
	print "$name\t$from{$name} failed attempts\n"
	}

print "\n";
for (keys %to) {
	print "$_\tpassword incorrectly typed $to{$_} times\n";
	}

