#!/bin/bash

statck=1

echo "`date` - starting"

while [[ $statck == 1 ]]; do
	if [`host www.google.com | grep alias | wc -l` != 1 ]; then
		echo "`date` - DSL Down"
	else
		echo "`date`"
	fi
	sleep 5m
done
