#!/bin/bash
#
# dump_wrapper
#
# usage: dump_wrapper file_system level tape_no
#

# Check syntax
if [[ $1 = "" ]] || [[ $2 = "" ]] || [[ $3 = "" ]]; then
	echo "usage: dump_wrapper file_system level tape_no"
else
	# Local definitions
	BKU=/usr/admin/backup

	# Perform the dump
	dump -$2au -f /dev/st0 -L $3 $1

	# Determine the Device Special File for the file system
	DSF=`df | egrep "$1$" | cut  -d " " -f 1,1`

	# Remove previous tape index entry
	cp $BKU/dump_index $BKU/dump_index.old
	egrep -v "^$3\b" $BKU/dump_index.old > $BKU/dump_index

	# Add new tape index entry
	HOST=`hostname -a`
	echo "$3	$1		$2	`date +%D-%T`	1" >> $BKU/dump_index

fi
