#!/bin/bash
#
#$Id: fuseradd 13 2012-02-08 16:06:31Z rohare $
#$URL: file:///usr/local/svn/admin/scripts/fuseradd $
#

MNT=/mnt/SaveConfig
HOST=`hostname -s`
Path=${MNT}/${HOST}/etc

if [ ! -d ${Path} ] ; then
	/bin/mount ${MNT}
	UnMount='y'
fi

for file in group passwd shadow; do
	while read line; do
		entry=`echo $line | cut -d: -f1,1`
		count=`egrep -c -e "^$entry:" /etc/$file`

		if (( $count > 1 )); then
			echo "Warning: More than one $file entry for $entry"
		fi

		if (( $count == 0 )) && [[ $file != 'group' ]] ; then
			echo $line >> /etc/$file
		fi

		if (( $count == 0 )) && [[ $file == 'group' ]] ; then
			echo $line >> /etc/group.new
		fi

		if [[ $file == 'group' ]] && (( $count == 1 )) ; then
			csl="${line//*:/}"
			list=`echo $csl | sed 's/,/ /g'`
			for member in $list; do
				if [[ ! ${line=~"[;,]$member"} ]] ; then
					line+=",${member}"
				fi
			done
			echo $line >> /etc/group.new
		fi

	done < ${Path}/$file
done

if [[ -r /etc/group.new ]]; then
	mv /etc/group.new /etc/group
fi

if [[ $UnMount == 'y' ]] ; then
	/bin/umount ${MNT}
fi
