#!/bin/ksh
#
#$Id: grp_cnt_chk 13 2012-02-08 16:06:31Z rohare $
#
# grp_cnt_chk
#
cat /etc/passwd | awk -F ":" '{ print $1 }' | \
	while read id ; do
		cnt=`grep $id /etc/group | grep -E -c -e "[,:]$id[,:]"`
		echo "$cnt, $id"
			
	done
