#!/usr/bin/perl
#$ID: $
#$Source: $
#
# This Perl script will parse through a generic twpol.txt file and
# create a custom version that only includes files that really exist.
# Output is to standard out, so redirect to desired file name.
#
open(SRC, "/etc/tripwire/twpol.txt") || die "Couldn't open /etc/tripwire/twpol.txt file!\n";

while (<SRC>) {
	chomp;

	$line = $_;
	s/^\s*#?\s*(\/\S+)\s.*$/$1/ && do {
		$fn = $_;
		if (-e $fn) {
			$line =~ s/^(\s*)#?(\s*\/\S+\s.*$)/$1$2/ ;
			print "$line\n" ;
		} else {
			$line =~ s/^(\s*)#?(\s*\/\S+\s.*$)/$1#$2/ ;
			print "$line\n" ;
		}
	next;
	};
	print "$_\n";
}
close SRC;
