#! /bin/bash
#$Id: onetime 13 2012-02-08 16:06:31Z rohare $
#$Source: /usr/admin/scripts/RCS/onetime,v $
#

ADMIN_DIR=/usr/admin
DIST=/var/dist
LABEL=SaveConfig

count=`grep -c "LABEL=${LABEL}\W" /etc/fstab`
method=`nodeattr -v backup`
backup_dir=`nodeattr -v backup_dir`

if (( $count == 1 && $method == 'local' )); then
	mnt_pt=`grep "LABEL=$LABEL\W" /etc/fstab | cut -f2,2`

	if [ ! -d $mnt_pt ]; then
		mkdir -m 755 $mnt_pt
	fi
	mount $mnt_pt

	if [ ! $backup_dir ]; then
		dest=${mnt_pt}/${HOST}
	else
		dest=${mnt_pt}/${backup_dir}/${HOST}
	fi


	# Backup newly installed OS configuration files
	DIRLST="/etc \
		/home \
		/root \
		/usr/local \
		/var/lib/mysql \
		/var/named \
		/var/spool/cron \
		/var/spool/mail \
		/var/www"

	ONETIME=${dest}/onetime
	if [[ ! -d ${ONETIME} ]] ; then
		mkdir ${ONETIME}
	fi

	for entry in ${DIRLST}; do
		rsync -avAX ${entry}/ ${ONETIME}/${entry}/
	done


	# Restore system from last backup
	RESTORE_LST="/home \
		/usr/admin \
		/usr/local \
		/var/lib/mysql \
		/var/named \
		/var/spool/cron \
		/var/spool/mail \
		/var/www"

	for entry in ${RESTORE_LST}; do
		rsync -avAX ${dest}/${entry}/ /${entry}/
	done


	# Restore iptables config file from backup
	cp -p ${dest}/etc/sysconfig/iptables /etc/sysconfig/iptables
	/sbin/service iptables restart

	# Run "make install" on the entire dist tree
	cd ${DIST}
	make install

	# Configure services
	${ADMIN_DIR}/scripts/chkconfiger

	# Unmount the backup filesystem
	umount ${mnt_pt}

else
	echo "No fstab entry contains $SafeConfig"
	echo "Unable to continue"
fi

