#!/bin/bash
# $Id: scrub 13 2012-02-08 16:06:31Z rohare $
# $URL: file:///usr/local/svn/admin/scripts/scrub $
#

x=1
i=0

while [ $x == 1 ]; do
	level=`df /var/tmp | grep "/var/tmp" | awk '{ print $4 }' | sed 's/%//'`
	echo $level
	if (( $level >= 100 )) ; then
		x=0
	fi
	cp /vmunix /var/tmp/vmunix.$i
	set i = ($i + 1)
done
