#!/usr/bin/perl
#
# level_1_dump
#
# Run interactively to get a level one dump of all file systems.
# The dumps are stored to disk files in location $DIR.

# Dump directory
$MPT = "/mnt/spare";
$DIR = "$MPT/dump_files";

`/sbin/dump -0u -f $DIR/root.dump /dev/hde9`;
`/sbin/dump -0u -f $DIR/boot.dump /dev/hde1`;
`/sbin/dump -0u -f $DIR/var.dump /dev/hde6`;
