#!/bin/bash
# $Id: StopPorn 13 2012-02-08 16:06:31Z rohare $
# $URL: file:///usr/local/svn/admin/scripts/StopPorn $
#
count=`/sbin/iptables -L ParentalControl -v | egrep -v -e 'Chain|pkts' | awk '{print $1}'`

if [ $count -gt 0 ]; then
	echo "Porn access, blocking eth1 internet access"
	/sbin/iptables -A Porn -i eth1 -s 192.168.2.0/255.255.255.0 -j REJECT
fi
