#!/bin/env bash
# suricata_alerts
#
# Set variables
Dir="/var/log/suricata"
logFile="eve.json"
sid=

#########################################################
# Help
#########################################################
Help()
{
	# Display Help
	echo "Suricata log reveiw."
	echo
	echo "Syntax: suricata_alerts [-d|f|h|s}"
	echo "options:"
	echo "d    Optional log file directory"
	echo "f    Optional log file name"
	echo "h    Print this help."
	echo "s    Optional SID to analyse"
	echo
}

#########################################################
# Alert summary report
#########################################################
Summary()
{
	# Alert summay
	Dir="$1"
	logFile="$2"
	echo "Alert summary for logfile: ${Dir}/${logFile}"
	if [[ ${logFile} == *.gz ]]; then
		zcat "${Dir}/${logFile}" | jq 'select(.event_type=="alert") | "\(.alert.signature_id) \(.alert.signature)"' | sort | uniq -c | sort -bgr
	else
		cat "${Dir}/${logFile}" | jq 'select(.event_type=="alert") | "\(.alert.signature_id) \(.alert.signature)"' | sort | uniq -c | sort -bgr
	fi
}

#########################################################
# SID review
#########################################################
SID()
{
	echo "Processing ${Dir}/${logFile} for SID $1"
	jqcmd="jq 'select(.alert.signature_id == [$1])'"
	cat ${Dir}/${logFile} | $jqcmd
}

#########################################################
# Process the input options.
#########################################################
# Get the options
while getopts "hd::f::s::" arg; do
	case $arg in
		d) # Log file directory
			Dir=${OPTARG}
			;;
		f) # Log file name
			logFile=${OPTARG}
			;;
		s) # SID to analyse
			sid=${OPTARG}
			;;
		h) # No option
			Help
			exit 0
			;;
	esac
done

if [ -z "${sid}" ]; then
	Summary "$Dir" "$logFile"
else
	SID "$sid"
fi
