#!/bin/bash
#
PATH=/bin:/usr/bin:/usr/sbin
REPORTDIR=/var/lib/tripwire/report

cd $REPORTDIR
report=`ls -1t | head -n 1`

echo "Updating tripwire database based on report:"
echo $report

tripwire -m u -a -r $report -P '<bart??>'
